#!/usr/bin/env python3
"""Extract the ROA296 letter font from roa296.rom into font296.h.

The SEM702 test loads this font into the SEM702 RAM chargen and renders it in
semigraphics mode.  Format: 128 glyphs x 16 dot-lines, char-major
(font296[ch*16 + line]) -- the same (charcode<<4)|line address the MAME
rc702 display_pixels forms.
"""
import sys

ROM = sys.argv[1] if len(sys.argv) > 1 else \
    "../../mame/roms/rc702/roa296.rom"
OUT = sys.argv[2] if len(sys.argv) > 2 else "font296.h"

data = open(ROM, "rb").read()
assert len(data) == 2048, f"expected 2048 bytes, got {len(data)}"

with open(OUT, "w") as f:
    f.write("/* ROA296 letter font extracted from roa296.rom: 128 glyphs x 16\n")
    f.write(" * dot-lines, char-major (font296[ch*16 + line]).\n")
    f.write(" * Generated by gen_font296.py -- do not edit. */\n")
    f.write("#define FONT_GLYPHS 128\n#define FONT_LINES 16\n")
    f.write("const unsigned char font296[128*16] = {\n")
    for i in range(0, len(data), 16):
        f.write("    " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print(f"wrote {OUT}")
