#!/usr/bin/env python3
"""Generate prog.c: a CP/M dual-checksum tool used to prove that CP/M reads
on-disk files byte-for-byte as z88dk-appmake laid them out (ravn/z88dk#36).

The program computes two structurally unrelated checksums (CRC-32 with poly
0xEDB88320, and FNV-1a-32) over BOTH:
  1. an in-memory deterministic payload  big[i] = (i*31+7) & 0xFF   (proves the
     loaded program image is intact in RAM), and
  2. its own file on the diskette, read via BDOS fopen/fread (proves CP/M reads
     the on-disk file exactly as laid out).

Usage:
    python3 gen_prog.py [ARRAY_SIZE] > prog.c

ARRAY_SIZE inflates the .COM to force multi-extent layout:
  * 0        -> tiny tool (~7.6 KB, single 16 KB extent)
  * 40000    -> ~48 KB .COM spanning 3 extents (exercises byte_size_extents=0
                word-pointer directory encoding, the fix verified in #36)

The array is emitted wrapped at 20 values/line: sccz80's preprocessor has a
line-length limit, so a single 150 KB initializer line fails to parse.
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 40000
if N >= 65536:
    sys.exit("ARRAY_SIZE must be < 65536 (16-bit index)")

vals = [(i * 31 + 7) & 0xFF for i in range(N)]

if N:
    body = "\n".join(
        "  " + ",".join(str(x) for x in vals[k:k + 20]) + ","
        for k in range(0, N, 20)
    )
    array_decl = f"const unsigned char big[ARR_N] = {{\n{body}\n}};\n"
    array_block = (
        "    /* 1) in-memory array checksum */\n"
        "    cksum_mem(big, ARR_N, &acrc, &afnv);\n"
        '    printf("ARR=big[]\\nABYTES=");   put_hex32(ARR_N);\n'
        '    printf("\\nACRC32=");            put_hex32(acrc);\n'
        '    printf("\\nAFNV32=");            put_hex32(afnv);\n'
        '    printf("\\n");\n'
    )
else:
    array_decl = ""
    array_block = ""

print(f'''#include <stdio.h>

/* CP/M dual-checksum tool (ravn/z88dk#36 on-disk verification).
 * Generated by gen_prog.py -- do not edit by hand. */

#define ARR_N {N}
static unsigned long crc_tab[256];

{array_decl}
static void crc_init(void) {{
    unsigned int i, j; unsigned long c;
    for (i = 0; i < 256; i++) {{
        c = (unsigned long)i;
        for (j = 0; j < 8; j++)
            c = (c & 1UL) ? (0xEDB88320UL ^ (c >> 1)) : (c >> 1);
        crc_tab[i] = c;
    }}
}}

static void put_hex32(unsigned long v) {{
    const char *hx = "0123456789ABCDEF"; int s;
    for (s = 28; s >= 0; s -= 4)
        putchar(hx[(int)((v >> s) & 0xFUL)]);
}}

/* Checksum a memory block. n fits in 16-bit unsigned (ARR_N < 65536). */
static void cksum_mem(const unsigned char *p, unsigned n,
                      unsigned long *pcrc, unsigned long *pfnv) {{
    unsigned long crc = 0xFFFFFFFFUL, fnv = 2166136261UL; unsigned i;
    for (i = 0; i < n; i++) {{
        unsigned char b = p[i];
        crc = crc_tab[(int)((crc ^ b) & 0xFFUL)] ^ (crc >> 8);
        fnv = (fnv ^ b) * 16777619UL;
    }}
    *pcrc = crc ^ 0xFFFFFFFFUL; *pfnv = fnv;
}}

int main(int argc, char **argv) {{
    const char *name = (argc > 1) ? argv[1] : "PROG.COM";
    FILE *f; unsigned char buf[128]; size_t n; unsigned int i;
    unsigned long crc = 0xFFFFFFFFUL, fnv = 2166136261UL, total = 0;
    unsigned long acrc, afnv; (void)acrc; (void)afnv;

    crc_init();

{array_block}
    /* 2) on-disk file checksum (self by default) */
    f = fopen(name, "rb");
    if (f == NULL) {{ printf("cannot open %s\\n", name); return 1; }}
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {{
        for (i = 0; i < n; i++) {{
            unsigned char b = buf[i];
            crc = crc_tab[(int)((crc ^ b) & 0xFFUL)] ^ (crc >> 8);
            fnv = (fnv ^ b) * 16777619UL;
        }}
        total += n;
    }}
    fclose(f);
    crc ^= 0xFFFFFFFFUL;

    printf("FILE=%s\\nBYTES=", name); put_hex32(total);
    printf("\\nCRC32=");             put_hex32(crc);
    printf("\\nFNV32=");             put_hex32(fnv);
    printf("\\n");
    return 0;
}}
''')
