#include <stdio.h>

/* CP/M dual-checksum tool (ravn/z88dk#36 on-disk verification).
 * Generated by gen_prog.py -- do not edit by hand. */

#define ARR_N 0
static unsigned long crc_tab[256];


static void crc_init(void) {
    unsigned int i, j; unsigned long c;
    for (i = 0; i < 256; i++) {
        c = (unsigned long)i;
        for (j = 0; j < 8; j++)
            c = (c & 1UL) ? (0xEDB88320UL ^ (c >> 1)) : (c >> 1);
        crc_tab[i] = c;
    }
}

static void put_hex32(unsigned long v) {
    const char *hx = "0123456789ABCDEF"; int s;
    for (s = 28; s >= 0; s -= 4)
        putchar(hx[(int)((v >> s) & 0xFUL)]);
}

/* Checksum a memory block. n fits in 16-bit unsigned (ARR_N < 65536). */
static void cksum_mem(const unsigned char *p, unsigned n,
                      unsigned long *pcrc, unsigned long *pfnv) {
    unsigned long crc = 0xFFFFFFFFUL, fnv = 2166136261UL; unsigned i;
    for (i = 0; i < n; i++) {
        unsigned char b = p[i];
        crc = crc_tab[(int)((crc ^ b) & 0xFFUL)] ^ (crc >> 8);
        fnv = (fnv ^ b) * 16777619UL;
    }
    *pcrc = crc ^ 0xFFFFFFFFUL; *pfnv = fnv;
}

int main(int argc, char **argv) {
    const char *name = (argc > 1) ? argv[1] : "PROG.COM";
    FILE *f; unsigned char buf[128]; size_t n; unsigned int i;
    unsigned long crc = 0xFFFFFFFFUL, fnv = 2166136261UL, total = 0;
    unsigned long acrc, afnv; (void)acrc; (void)afnv;

    crc_init();


    /* 2) on-disk file checksum (self by default) */
    f = fopen(name, "rb");
    if (f == NULL) { printf("cannot open %s\n", name); return 1; }
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
        for (i = 0; i < n; i++) {
            unsigned char b = buf[i];
            crc = crc_tab[(int)((crc ^ b) & 0xFFUL)] ^ (crc >> 8);
            fnv = (fnv ^ b) * 16777619UL;
        }
        total += n;
    }
    fclose(f);
    crc ^= 0xFFFFFFFFUL;

    printf("FILE=%s\nBYTES=", name); put_hex32(total);
    printf("\nCRC32=");             put_hex32(crc);
    printf("\nFNV32=");             put_hex32(fnv);
    printf("\n");
    return 0;
}

