/* cpnos-rom PROM relocator (C23) — data-driven via payload header.
 *
 * Reads `payload_header` (emitted by tasks/scripts/genpayload_header.py
 * from the linked payload's symbols) and acts on the values found there:
 *   - resident_dest, chunk_a/b src+size: where to copy the resident
 *   - bss_pairs: which RAM regions to zero before checksum
 *   - cold_entry: where to JP after relocation
 *   - checksum_magic: the target value for the word-additive sum
 *
 * No --defsym injection, no hardcoded addresses.  The linker (payload.ld
 * + the header generator) is the single source of truth.  Adding a new
 * BSS region or page-aligned reservation requires touching ONLY the
 * payload linker script + the header generator script — no Makefile
 * edits, no awk extraction, no underscore-counting Z80-ABI traps.
 *
 * Embedding mechanism — same source for clang and SDCC:
 *   `#include "name.inc"` where each `.inc` is a comma-separated byte
 *   stream generated by `tasks/scripts/bin2inc.py` from the matching
 *   `.bin`.  Found via `-I$(BUILDDIR)` per compiler.  C23 `#embed`
 *   would be cleaner but SDCC doesn't implement it.
 *
 * Why two chunks for the resident?  The Z80 maps PROM0 at
 * 0x0000..0x07FF and PROM1 at 0x2000..0x27FF, with a 6 KB address
 * hole in between.  The resident is a single contiguous blob; the
 * build splits payload.bin into payload_a.bin (PROM0 tail) and
 * payload_b.bin (PROM1), each #embed'd into its own linker-placed
 * section.  The relocator copies them both back into one contiguous
 * range at `resident_dest` (read from the header).
 *
 * Entry flow:
 *   reset.s (at 0x0000) DI + SP + jp _relocate  ->  this function
 *   relocate() reads header -> memcpy chunk A & B -> zero bss_pairs ->
 *   verify checksum -> JP cold_entry
 */
#include <stdint.h>
#include <stddef.h>
#include "compiler/compat.h"
#include "hal.h"
#include "payload_header.h"

/* Header — emitted by tasks/scripts/genpayload_header.py into the
 * .payload_header section, placed by relocator.ld right after the
 * relocator code in PROM0.  Linker-resolved at relocator-link time. */
extern const struct payload_header payload_header;

/* Chunk-byte embeds — clang only.
 *
 * Under clang, the relocator is its own link separate from the resident
 * payload.elf, so the chunk bytes have to be #include'd as `.inc` files
 * (generated from .bin by tasks/scripts/bin2inc.py) into PROM0/PROM1
 * sections that the relocator linker pins to the right LMAs.
 *
 * Under SDCC the build is single-link: the resident, the relocator, and
 * the header all link in one z88dk pass and the resident bytes already
 * live in their own RESIDENT_* sections.  No embeds — the linker knows
 * where everything is and the gen-header script writes those addresses
 * into the header.  Including these arrays under SDCC would emit
 * duplicate bytes in unrelated sections. */
#if defined(__clang__) && defined(__z80__)
/* Init image: lives at PROM 0 0x0200 -- linked at the same VMA as
 * the .init output section in payload.elf so absolute references
 * inside init code resolve.  Never copied to RAM; runs in place
 * from PROM until PROM disable. */
SECTION_PROM0_INIT
static const uint8_t init_image[] = {
#include "init.inc"
};

/* Chunk A: first chunk_a_size bytes of resident payload.  Lives
 * in PROM0 tail; relocator.ld emits __chunk_a_start at this section's
 * load address so the header's `chunk_a_src` field resolves to the
 * actual placement (no hardcoded 0x0400).  Header tells us the size. */
SECTION_PROM0_TAIL
static const uint8_t payload_a[] = {
#include "payload_a.inc"
};

/* Chunk B: remaining resident payload bytes.  Lives in PROM1.
 * relocator.ld emits __chunk_b_start at this section's load address. */
SECTION_PROM1
static const uint8_t payload_b[] = {
#include "payload_b.inc"
};
#endif

/* "BAD CHECKSUM" message copied into display memory at 0xF800 when
 * the integrity check fails — appears at the top-left of the screen
 * and is visible to mame_boot_test.lua's display-memory probe. */
static const char BAD_CHECKSUM_MSG[] = "BAD CHECKSUM";

/* Minimum 8237 DMA + 8275 CRT init to drive display memory at 0xF800
 * visibly.  Subset of init_hardware's port_init table -- only the
 * channels that drive the screen, no IRQ enables, no SIO setup, no
 * CTC (relocator runs DI and never refreshes the screen via an ISR).
 * Runs as the FIRST thing in relocate() so the build_date_str /
 * "PROM MISMATCH" / "BAD CHECKSUM" messages later in the function
 * reach the operator regardless of whether the 8275 was in its
 * default-display state at power-on.  Pairs (port, value), iterated
 * by an inline loop -- same shape as init.c's port_init table.
 * Port numbers are 8-bit literals here (memory addresses go through
 * symbolic constants per HARD RULE feedback_no_literal_addresses,
 * port numbers are an explicit exception). */
/* Non-static so the asm symbol `_reloc_display_init` is emitted at
 * file-global scope.  `static const` would land in the same .rodata
 * but with internal linkage; clang Z80 then can't resolve the asm
 * `ld hl, _reloc_display_init` reference inside the inline asm
 * below (the C-side has no use of the address, so the compiler
 * has nothing to anchor an internal symbol to). */
const uint8_t reloc_display_init[] = {
    /* 8237 DMA: master clear, ch2 single mem->IO autoinit, base/wc
     * pointing at display memory, unmask ch2. */
    PORT_DMA_CMD,        0x20,
    PORT_DMA_MODE,       0x58 | 2,
    PORT_DMA_CLBP,       0,
    PORT_DMA_CH2_ADDR,   DISPLAY_ADDR & 0xFF,
    PORT_DMA_CH2_ADDR,   (DISPLAY_ADDR >> 8) & 0xFF,
    PORT_DMA_CH2_WC,     (DISPLAY_SIZE - 1) & 0xFF,
    PORT_DMA_CH2_WC,     ((DISPLAY_SIZE - 1) >> 8) & 0xFF,
    PORT_DMA_SMSK,       0x02,
    /* 8275 CRT: reset (cmd=0x00), 4 geometry params, enable inter-
     * rupts (cmd=0xE0; harmless, we stay DI), start (cmd=0x23). */
    PORT_CRT_CMD,    0x00,
    PORT_CRT_PARAM,  0x4F,
    PORT_CRT_PARAM,  0x98,
    PORT_CRT_PARAM,  0x7A,
    PORT_CRT_PARAM,  0x6D,
    PORT_CRT_CMD,    0xE0,
    PORT_CRT_CMD,    0x23,
};

#ifdef CPNOS_HAS_P1_HEADER
/* Duplicate header at PROM1 byte 0 (LMA 0x2000), emitted by
 * gen_payload_header.py into .payload_header_p1 and anchored by
 * relocator.ld.  Same bytes as `payload_header` in PROM0; the
 * relocator compares them word-by-word at boot to detect
 * cross-PROM mismatch (e.g. PROM0 from build N-1 + PROM1 from
 * build N).  C name has no leading underscore so clang's
 * `_<name>` mangling rule lines up with the asm symbol
 * `_payload_header_p1` emitted by gen_payload_header.py. */
extern const struct payload_header payload_header_p1;
static const char PROM_MISMATCH_MSG[] = "PROM MISMATCH";
#endif

/* Zero `len` bytes starting at `dst`.  Replaces __builtin_memset for
 * portability:
 *
 *   - Clang Z80: __builtin_memset already lowers to inline LDIR-from-
 *     self, so this wrapper just delegates.
 *   - SDCC z88dk: __builtin_memset gets mapped to z88dk's `_memset`,
 *     which is the sdcccall=0 (stack-arg) entry point.  Under
 *     sdcccall=1 the compiler emits a register+stack-mix calling
 *     convention that does not match `_memset`'s `pop hl/de/bc`
 *     preamble -- you get garbage args, no zeroing, and a wrong SP
 *     on return.  Side-step the whole library by writing the LDIR-
 *     from-self loop inline as a naked sdcccall(1) function so the
 *     relocator is self-contained.
 *
 * sdcccall(1) for `relocator_zero(void *dst, uint16_t len)` puts the
 * first arg in HL and the second in DE -- exactly what the asm uses. */
#if defined(__SDCC) || defined(__SCCZ80)
static void relocator_zero(void *dst, uint16_t len) __naked
{
    (void)dst;
    (void)len;
    __asm
        ld   a, d
        or   a, e
        ret  z
        ld   (hl), 0
        ld   b, d
        ld   c, e
        dec  bc
        ld   a, b
        or   a, c
        ret  z
        ld   d, h
        ld   e, l
        inc  de
        ldir
        ret
    __endasm;
}
#else
static inline void relocator_zero(void *dst, uint16_t len) {
    __builtin_memset(dst, 0, len);
}
#endif

/* Tail-called from reset.s.  SP is already set to __stack_top by
 * reset.s.  PROMs are still mapped — the payload disables them later.
 *
 * Flow (preserves the LDIR → BSS → checksum → JP ordering invariant
 * documented at the top of this file; checksum AFTER BSS-clear so a
 * runaway clear surfaces as BAD CHECKSUM rather than silent
 * post-handoff corruption):
 *   1. Sanity-check header magic.
 *   2. memcpy chunk A then chunk B to resident_dest (read from header).
 *   3. Zero each (start, end) pair in bss_pairs[] until sentinel.
 *   4. Verify word-additive checksum equals header.checksum_magic.
 *   5. Mismatch: copy "BAD CHECKSUM" to display memory, busy-loop.
 *   6. Match: tail-call header.cold_entry.
 *
 * Compactness — every helper is inlined into this function so the
 * relocator stays under the 256 B PROM0 budget (next section
 * .prom0_init starts at 0x100).  C locals live on the actual stack
 * (file compiled without `+static-stack`).
 */
NORETURN void relocate(void) {
    const struct payload_header *h = &payload_header;

    /* Magic check.  Halts loudly on stale/missing/corrupt header. */
    if (h->magic != PAYLOAD_HEADER_MAGIC) for (;;) { }

    /* Display init -- programs the 8237 DMA ch2 + 8275 CRT so the
     * subsequent build_date_str stamp / PROM-MISMATCH / BAD-CHECKSUM
     * messages are visible.  Runs DI; safe before any other setup.
     *
     * Hand-coded asm because the relocator builds without
     * +static-stack: a C-level for-loop with `_port_out(port, val)`
     * lowers to ~90 B of stack-relative spill code on clang Z80
     * (locals via `push hl; ld hl,N; add hl,sp; ...`).  The asm
     * loop below is ~10 B and uses OUT (C),A which the C-level
     * `_port_out(uint16_t)` indirectly emits anyway.  Both
     * compilers see identical 8-bit port + 8-bit value pairs from
     * the reloc_display_init[] table.  Iteration count is hard-
     * coded (SDCC's __asm__ doesn't support GCC extended-asm
     * operand placeholders); STATIC_ASSERT below guarantees the
     * count matches the table. */
    STATIC_ASSERT(sizeof(reloc_display_init) == 30,
                  "reloc_display_init size changed -- update djnz count below");
    ASM_VOLATILE(
        "ld   hl, _reloc_display_init\n\t"
        "ld   b, 15\n\t"
        "l_reloc_disp_loop:\n\t"
        "ld   c, (hl)\n\t"
        "inc  hl\n\t"
        "ld   a, (hl)\n\t"
        "inc  hl\n\t"
        "out  (c), a\n\t"
        "djnz l_reloc_disp_loop\n\t"
    );

    /* Stamp the build date into display memory at row 0, columns 0..15.
     * The 8275 CRT controller drives the screen from RAM at 0xF800 in
     * its hardware-reset state, so the operator sees this string AT
     * BOOT -- before SIO-B is initialised, before any resident-code
     * banner runs.  If a later step in the relocator hangs (e.g. a
     * BAD CHECKSUM) the operator can read off which build was being
     * relocated when the hang happened.  16 bytes verbatim, no
     * brackets / no terminator.  Any later relocator failure that
     * writes its own message (e.g. "BAD CHECKSUM" at column 0)
     * overwrites the prefix, so the build date moves to a later
     * column position only if we want both visible -- today, the
     * BAD CHECKSUM print clobbers it, which is fine: the failure
     * message takes priority for a halted boot. */
    __builtin_memcpy((void *)0xF800, h->build_date_str,
                     sizeof h->build_date_str);

#ifdef CPNOS_HAS_P1_HEADER
    /* Cross-PROM mismatch check.  Word-wise compare across the
     * fixed-portion header (the variable-length bss_pairs is a
     * flexible array, excluded from sizeof).  Any mismatch in
     * magic/version/resident_dest/chunk_*_src/chunk_*_size/
     * cold_entry/checksum_magic/build_date_str surfaces here.  Open-
     * coded inline to keep the relocator within its 512 B PROM0
     * reservation.  Halts before any chunk copy. */
    {
        const uint16_t *a = (const uint16_t *)h;
        const uint16_t *b = (const uint16_t *)&payload_header_p1;
        for (uint16_t i = sizeof(struct payload_header) >> 1; i; --i) {
            if (*a++ != *b++) {
                __builtin_memcpy((void *)0xF800, PROM_MISMATCH_MSG,
                                 sizeof PROM_MISMATCH_MSG - 1);
                for (;;) { }
            }
        }
    }
#endif

    /* Chunk A, then chunk B. */
    uint8_t *dest = (uint8_t *)h->resident_dest;
    __builtin_memcpy(dest,
                     (const void *)h->chunk_a_src, h->chunk_a_size);
    __builtin_memcpy(dest + h->chunk_a_size,
                     (const void *)h->chunk_b_src, h->chunk_b_size);

    /* BSS-pair clear, terminated by sentinel.  Before the checksum
     * by design (see top-of-file invariant). */
    const uint16_t (*p)[2] = h->bss_pairs;
    while ((*p)[0] != PAYLOAD_BSS_SENTINEL) {
        relocator_zero((void *)(*p)[0],
                       (uint16_t)((*p)[1] - (*p)[0]));
        p++;
    }

    /* Word-additive sum of the relocated payload.  Inlined to avoid
     * the helper-function overhead. */
    uint16_t total = h->chunk_a_size + h->chunk_b_size;
    const volatile uint16_t *w = (const volatile uint16_t *)dest;
    uint16_t sum = 0;
    for (uint16_t i = total >> 1; i; --i, ++w) sum += *w;

    if (sum != h->checksum_magic) {
        __builtin_memcpy((void *)0xF800, BAD_CHECKSUM_MSG,
                         sizeof BAD_CHECKSUM_MSG - 1);
        for (;;) { }
    }

    /* JP cold entry.
     *
     * Clang Z80: an ordinary function-pointer call lowers to the
     * `__call_iy` runtime helper, which we don't link in.  Force a
     * direct `jp (hl)` via a register-pinned local + inline asm; this
     * is also a true tail-jump (no stack frame, no return address
     * pushed for an entry that never returns).
     *
     * SDCC z88dk: the function-pointer call lowers cleanly (no runtime
     * helper).  The 2 bytes of return-address stack the call pushes are
     * irrelevant — cold_entry never returns and the resident handoff
     * resets SP at PROM-disable time.  The portable spelling is also
     * the one that survives -Werror on the host LSP build. */
#if defined(__clang__) && defined(__z80__)
    register uint16_t entry __asm__("hl") = h->cold_entry;
    __asm__ volatile ("jp (hl)" : : "r"(entry));
#else
    ((void (*)(void))h->cold_entry)();
#endif
    for (;;) { }   /* unreachable; satisfies NORETURN */
}
