/* cpnos-rom PROM relocator (C23) — data-driven via payload header.
 *
 * Reads `payload_header` (emitted by tasks/scripts/genpayload_header.py
 * from the linked payload's symbols) and acts on the values found there:
 *   - resident_dest, chunk_a/b src+size: where to copy the resident
 *   - bss_pairs: which RAM regions to zero before checksum
 *   - cold_entry: where to JP after relocation
 *   - checksum_magic: the target value for the word-additive sum
 *
 * No --defsym injection, no hardcoded addresses.  The linker (payload.ld
 * + the header generator) is the single source of truth.  Adding a new
 * BSS region or page-aligned reservation requires touching ONLY the
 * payload linker script + the header generator script — no Makefile
 * edits, no awk extraction, no underscore-counting Z80-ABI traps.
 *
 * Embedding mechanism — same source for clang and SDCC:
 *   `#include "name.inc"` where each `.inc` is a comma-separated byte
 *   stream generated by `tasks/scripts/bin2inc.py` from the matching
 *   `.bin`.  Found via `-I$(BUILDDIR)` per compiler.  C23 `#embed`
 *   would be cleaner but SDCC doesn't implement it.
 *
 * Why two chunks for the resident?  The Z80 maps PROM0 at
 * 0x0000..0x07FF and PROM1 at 0x2000..0x27FF, with a 6 KB address
 * hole in between.  The resident is a single contiguous blob; the
 * build splits payload.bin into payload_a.bin (PROM0 tail) and
 * payload_b.bin (PROM1), each #embed'd into its own linker-placed
 * section.  The relocator copies them both back into one contiguous
 * range at `resident_dest` (read from the header).
 *
 * Entry flow:
 *   reset.s (at 0x0000) DI + SP + jp _relocate  ->  this function
 *   relocate() reads header -> memcpy chunk A & B -> zero bss_pairs ->
 *   verify checksum -> JP cold_entry
 */
#include <stdint.h>
#include <stddef.h>
#include "compiler/compat.h"
#include "payload_header.h"

/* Header — emitted by tasks/scripts/genpayload_header.py into the
 * .payload_header section, placed by relocator.ld right after the
 * relocator code in PROM0.  Linker-resolved at relocator-link time. */
extern const struct payload_header payload_header;

/* Init image: lives at PROM 0 0x0100 -- linked at the same VMA as
 * the .init output section in payload.elf so absolute references
 * inside init code resolve.  Never copied to RAM; runs in place
 * from PROM until PROM disable.  See tasks/todo.md, step 3. */
SECTION_PROM0_INIT
static const uint8_t init_image[] = {
#include "init.inc"
};

/* Chunk A: first chunk_a_size bytes of resident payload.  Lives
 * in PROM0 tail; relocator.ld emits __chunk_a_start at this section's
 * load address so the header's `chunk_a_src` field resolves to the
 * actual placement (no hardcoded 0x0400).  Header tells us the size. */
SECTION_PROM0_TAIL
static const uint8_t payload_a[] = {
#include "payload_a.inc"
};

/* Chunk B: remaining resident payload bytes.  Lives in PROM1.
 * relocator.ld emits __chunk_b_start at this section's load address. */
SECTION_PROM1
static const uint8_t payload_b[] = {
#include "payload_b.inc"
};

/* "BAD CHECKSUM" message copied into display memory at 0xF800 when
 * the integrity check fails — appears at the top-left of the screen
 * and is visible to mame_boot_test.lua's display-memory probe. */
static const char BAD_CHECKSUM_MSG[] = "BAD CHECKSUM";

/* Tail-called from reset.s.  SP is already set to __stack_top by
 * reset.s.  PROMs are still mapped — the payload disables them later.
 *
 * Flow (preserves the LDIR → BSS → checksum → JP ordering invariant
 * documented at the top of this file; checksum AFTER BSS-clear so a
 * runaway clear surfaces as BAD CHECKSUM rather than silent
 * post-handoff corruption):
 *   1. Sanity-check header magic.
 *   2. memcpy chunk A then chunk B to resident_dest (read from header).
 *   3. Zero each (start, end) pair in bss_pairs[] until sentinel.
 *   4. Verify word-additive checksum equals header.checksum_magic.
 *   5. Mismatch: copy "BAD CHECKSUM" to display memory, busy-loop.
 *   6. Match: tail-call header.cold_entry.
 *
 * Compactness — every helper is inlined into this function so the
 * relocator stays under the 256 B PROM0 budget (next section
 * .prom0_init starts at 0x100).  C locals live on the actual stack
 * (file compiled without `+static-stack`).
 */
NORETURN void relocate(void) {
    const struct payload_header *h = &payload_header;

    /* Magic check.  Halts loudly on stale/missing/corrupt header. */
    if (h->magic != PAYLOAD_HEADER_MAGIC) for (;;) { }

    /* Chunk A, then chunk B. */
    uint8_t *dest = (uint8_t *)h->resident_dest;
    __builtin_memcpy(dest,
                     (const void *)h->chunk_a_src, h->chunk_a_size);
    __builtin_memcpy(dest + h->chunk_a_size,
                     (const void *)h->chunk_b_src, h->chunk_b_size);

    /* BSS-pair clear, terminated by sentinel.  Before the checksum
     * by design (see top-of-file invariant). */
    const uint16_t (*p)[2] = h->bss_pairs;
    while ((*p)[0] != PAYLOAD_BSS_SENTINEL) {
        __builtin_memset((void *)(*p)[0], 0,
                         (size_t)((*p)[1] - (*p)[0]));
        p++;
    }

    /* Word-additive sum of the relocated payload.  Inlined to avoid
     * the helper-function overhead. */
    uint16_t total = h->chunk_a_size + h->chunk_b_size;
    const volatile uint16_t *w = (const volatile uint16_t *)dest;
    uint16_t sum = 0;
    for (uint16_t i = total >> 1; i; --i, ++w) sum += *w;

    if (sum != h->checksum_magic) {
        __builtin_memcpy((void *)0xF800, BAD_CHECKSUM_MSG,
                         sizeof BAD_CHECKSUM_MSG - 1);
        for (;;) { }
    }

    /* JP cold entry.  Inline asm avoids the clang Z80 indirect-call
     * runtime helper (`__call_iy`) that an ordinary function-pointer
     * call would lower to — keeps the relocator self-contained and
     * leaves the cold entry as a tail-jump (no stack frame). */
    register uint16_t entry __asm__("hl") = h->cold_entry;
    __asm__ volatile ("jp (hl)" : : "r"(entry));
    for (;;) { }   /* unreachable; satisfies NORETURN */
}
