#!/usr/bin/env python3
"""Emit payload_header_data.s for the cpnos-rom relocator stage.

Reads symbols from the payload link (clang's payload.elf via llvm-nm, OR
SDCC's cpnos_payload.map directly) and emits an assembly file that
defines the `_payload_header` struct at PROM offset 0 of its containing
section.  Both relocator pipelines link this generated .s into the PROM
image so the relocator can read its metadata at boot — replacing the
old `--defsym` injection (clang) and `prom_loader.asm` hardcoded
literals (SDCC).

The header layout matches `cpnos-rom/payload_header.h`:
  +0  magic       0x6350
  +2  version     0x0001
  +4  resident_dest    = _bios_boot
  +6  chunk_a_src      = (linker-emitted later — see notes)
  +8  chunk_a_size     = (passed in via --chunk-a-size)
  +10 chunk_b_src      = (linker-emitted later)
  +12 chunk_b_size     = (computed from payload-size − chunk-a-size)
  +14 cold_entry       = _cpnos_cold_entry
  +16 checksum_magic   = 0xCAFE
  +18 bss_pairs[]      = pairs (start, end), terminated by (0xFFFF, 0xFFFF)

`chunk_a_src` and `chunk_b_src` are NOT resolved by this script — they
are the addresses where chunk A and chunk B *physically land* in the
relocator's PROM binary, which the relocator linker decides.  We emit
asm references like `defw __chunk_a_start` so the linker resolves them
when assembling the relocator image.  The symbols `__chunk_a_start`
and `__chunk_b_start` must be defined by the relocator linker script
(e.g. via `__chunk_a_start = .;` immediately before the chunk A INCBIN).

This separation matches the architectural invariant: the payload link
knows nothing about PROMs; PROM addresses are stage-2 concerns.

Usage:
    gen_payload_header.py --syntax=clang|sdcc \
                          --payload-elf=path/payload.elf | --map=path/cpnos_payload.map \
                          --payload-bin=path/payload.bin \
                          --chunk-a-size=N \
                          [--include-ivt] \
                          --out=path/payload_header_data.s
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


def read_symbols_from_elf(elf_path: str, llvm_nm: str) -> dict[str, int]:
    """Run llvm-nm on the payload ELF and return a {name: address} dict."""
    out = subprocess.check_output([llvm_nm, "--defined-only", elf_path],
                                  text=True)
    syms = {}
    for line in out.splitlines():
        # Format: "ADDR T name" where T is the symbol type letter.
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            addr = int(parts[0], 16)
        except ValueError:
            continue
        name = parts[2]
        syms[name] = addr
    return syms


def read_symbols_from_map(map_path: str) -> dict[str, int]:
    """Parse a z88dk-z80asm .map file and return a {name: address} dict.

    Map line format example:
        _bios_boot                      = $EE00 ; addr, public, , ...
    """
    syms = {}
    rx = re.compile(r"^(\S+)\s*=\s*\$([0-9A-Fa-f]+)\s*;\s*addr\s*,")
    for line in Path(map_path).read_text().splitlines():
        m = rx.match(line)
        if m:
            syms[m.group(1)] = int(m.group(2), 16)
    return syms


def fmt_clang(out, fields):
    """Emit GAS-Z80 dialect (clang)."""
    out.write("; Generated by gen_payload_header.py — DO NOT EDIT.\n")
    out.write("; Header layout matches cpnos-rom/payload_header.h.\n\n")
    out.write('.section .payload_header,"a",@progbits\n')
    out.write(".global _payload_header\n")
    out.write("_payload_header:\n")
    for name, value in fields:
        comment = f"  ; {name}" if name else ""
        if isinstance(value, str):
            out.write(f"    .short {value}{comment}\n")
        else:
            out.write(f"    .short {value:#06x}{comment}\n")


def fmt_sdcc(out, fields):
    """Emit z88dk-z80asm dialect (SDCC)."""
    out.write("; Generated by gen_payload_header.py — DO NOT EDIT.\n")
    out.write("; Header layout matches cpnos-rom/payload_header.h.\n\n")
    out.write("    SECTION PAYLOAD_HEADER\n")
    out.write("    PUBLIC _payload_header\n")
    out.write("_payload_header:\n")
    for name, value in fields:
        comment = f"  ; {name}" if name else ""
        if isinstance(value, str):
            out.write(f"    defw {value}{comment}\n")
        else:
            out.write(f"    defw {value:#06x}{comment}\n")


# Magic / version / sentinel — must match cpnos-rom/payload_header.h.
MAGIC = 0x6350
VERSION = 0x0001
CHECKSUM_MAGIC = 0xCAFE
SENTINEL = 0xFFFF


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--syntax", choices=("clang", "sdcc"), required=True)
    p.add_argument("--payload-elf", help="Path to payload.elf (clang)")
    p.add_argument("--map", help="Path to cpnos_payload.map (SDCC)")
    p.add_argument("--payload-bin", required=True,
                   help="Path to payload.bin (used to compute total size)")
    p.add_argument("--chunk-a-size", type=int, required=True,
                   help="dd-split boundary in bytes (e.g. 1024)")
    p.add_argument("--llvm-nm", default="llvm-nm",
                   help="llvm-nm binary (clang only)")
    p.add_argument("--include-ivt", action="store_true",
                   help="Add (__ivt_start, __ivt_end) to bss_pairs")
    p.add_argument("--out", required=True)
    args = p.parse_args()

    if args.syntax == "clang":
        if not args.payload_elf:
            p.error("--payload-elf required for --syntax=clang")
        syms = read_symbols_from_elf(args.payload_elf, args.llvm_nm)
    else:
        if not args.map:
            p.error("--map required for --syntax=sdcc")
        syms = read_symbols_from_map(args.map)

    payload_size = os.path.getsize(args.payload_bin)
    chunk_a_size = args.chunk_a_size
    chunk_b_size = payload_size - chunk_a_size
    if chunk_b_size < 0:
        sys.exit(f"chunk-a-size {chunk_a_size} exceeds payload-bin size {payload_size}")

    def sym(name):
        if name not in syms:
            sys.exit(f"missing symbol in payload link: {name}")
        return syms[name]

    # The Z80 ABI prepends `_` to C symbols.  llvm-nm reports the
    # post-mangle name (single underscore on most C symbols, double on
    # C extern arrays declared `__name[]`).  z88dk's map shows the
    # same names.  Use the post-mangle spelling here.
    fields = [
        ("magic",          MAGIC),
        ("version",        VERSION),
        ("resident_dest",  sym("_bios_boot")),
        ("chunk_a_src",    "__chunk_a_start"),    # linker-resolved at relocator-link
        ("chunk_a_size",   chunk_a_size),
        ("chunk_b_src",    "__chunk_b_start"),    # linker-resolved at relocator-link
        ("chunk_b_size",   chunk_b_size),
        ("cold_entry",     sym("_cpnos_cold_entry")),
        ("checksum_magic", CHECKSUM_MAGIC),
        # BSS pairs to zero before checksum.
        ("scratch_bss_start", sym("__scratch_bss_start")),
        ("scratch_bss_end",   sym("__scratch_bss_end")),
        ("pio_rx_bss_start",  sym("__pio_rx_bss_start")),
        ("pio_rx_bss_end",    sym("__pio_rx_bss_end")),
    ]
    if args.include_ivt:
        fields += [
            ("ivt_start", sym("__ivt_start")),
            ("ivt_end",   sym("__ivt_end")),
        ]
    # Sentinel pair.
    fields += [
        ("sentinel", SENTINEL),
        ("sentinel", SENTINEL),
    ]

    with open(args.out, "w") as out:
        if args.syntax == "clang":
            fmt_clang(out, fields)
        else:
            fmt_sdcc(out, fields)

    print(f"gen_payload_header: wrote {args.out} ({len(fields)} fields, "
          f"chunk_a={chunk_a_size} chunk_b={chunk_b_size}, "
          f"payload_size={payload_size})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
